name: Unity Windows Build

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:
  buildWindows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      # ----------------------------------------
      # Checkout repository
      # ----------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # ----------------------------------------
      # Cache Unity Library
      # ----------------------------------------
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: QA Unity Project/Library
          key: Library-Windows-${{ hashFiles('QA Unity Project/Packages/packages-lock.json') }}
          restore-keys: |
            Library-Windows-

      # ----------------------------------------
      # Build Unity Project
      # ----------------------------------------
      - name: Build Windows
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

        with:
          projectPath: QA Unity Project
          targetPlatform: StandaloneWindows64
          buildName: QAUnityProject
          buildsPath: build
          versioning: None

      # ----------------------------------------
      # Upload Build Artifact
      # ----------------------------------------
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: QAUnityProject-Windows
          path: build/StandaloneWindows64
          if-no-files-found: error
